apiVersion: 1
datasources:
  - name: Loki # Отображаемое имя нашего источника данных
    type: loki # Тип источника
    access: proxy #
    orgId: 1 # Идентификатор организации (единица адм. деления в Grafana) которой будет доступен источник
    url: http://loki:3100 # Адрес откуда получать данные (здесь мы используем имя сервиса loki, т. к. компоуз создаст свою сеть в которой к контейнерам можно обращаться по имени compose-сервиса)
    basicAuth: false # Для удобства демонстрации в Loki отключена авторизация, поэтому и тут она не зачем
    isDefault: true #
    version: 1 #
    editable: false # Зпретим редактирование через интерфейс Grafana
